### ISSUE TITLE
Erreur : server_data_loader.lua | attempt to compare two nil values 

### ISSUE THREAD

**Issue by UnknowColum** [iTexZoz/fivem_roleplay_core#5]
Hello iTexZoz<p>

everything and in the title, I have a problem when starting the server with five_roleplay_core.<p>

Erreur : https://gist.github.com/UnknowColum/a7df2e8504aed17ee8b07c27047cca73 <p>

Need Help 👍 <p>

**Comment by iTexZoz** [comment]
Hello,
first of all thank you for the attention paid to five_roleplay_core

Your problem is under study.

I will let you know

**Comment by iTexZoz** [comment]
Problem solved.

please update your five roleplay core

https://github.com/iTexZoz/fivem_roleplay_core/releases
